// eslint-disable-next-line @typescript-eslint/no-var-requires
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      sans: ['var(--font-inter)', ...defaultTheme.fontFamily.sans],
      title: ['var(--font-inter)', ...defaultTheme.fontFamily.sans],
      mono: ['var(--font-jetbrains-mono)', ...defaultTheme.fontFamily.mono],
    },
    lineHeight: {
      ...defaultTheme.lineHeight,
      dense: '1.125',
    },
    letterSpacing: {
      tightest: '0.04em',
      tighter: '0.025em',
      tight: '0.01em',
      normal: '0',
    },
    spacing: {
      ...defaultTheme.spacing,
      4.5: '18px',
      6.25: '25px',
      6.5: '26px',
      8.5: '34px',
      9.5: '38px',
      10.5: '42px',
      12.5: '50px',
      13: '52px',
      15: '60px',
      18: '72px',
      19: '76px',
      19.5: '78px',
      20.5: '82px',
      21: '84px',
      22: '88px',
      25: '100px',
      26: '104px',
      30: '120px',
      34: '136px',
      46: '184px',
      50: '200px',
    },
    fontSize: {
      ...defaultTheme.fontSize,
      4: '4px',
      8: '8px',
      9: '9px',
      10: '10px',
      11: '11px',
      12: '12px',
      13: '13px',
      14: '14px',
      15: '15px',
      16: '16px',
      17: '17px',
      18: '18px',
      19: '19px',
      20: '20px',
      22: '22px',
      24: '24px',
      28: '28px',
      32: '32px',
      36: '36px',
      40: '40px',
      44: '44px',
      46: '46px',
      48: '48px',
      54: '54px',
      56: '56px',
      60: '60px',
      64: '64px',
      72: '72px',
      80: '80px',
      88: '88px',
    },
    colors: ({ colors }) => ({
      ...colors,
      gray: {
        5: 'hsl(220 12% 5%)',
        8: 'hsl(228 12% 8%)',
        12: 'hsl(230 10% 12%)',
        15: 'hsl(210 5% 15%)',
        20: 'hsl(228 10% 20%)',
        30: 'hsl(231 8% 30%)',
        40: 'hsl(229 8% 40%)',
        50: 'hsl(229 7% 50%)',
        60: 'hsl(229 8% 60%)',
        70: 'hsl(225 8% 70%)',
        80: 'hsl(228 10% 80%)',
        90: 'hsl(230 12% 90%)',
        94: 'hsl(220 10% 94%)',
        98: 'hsl(210 20% 98%)',
      },
      blue: '#7C78DE',
      'blue-light': '#7D7DE8',
      orange: '#FF8126',
    }),
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      backgroundImage: {},
      borderRadius: {
        10: '10px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      screens: {
        xs: '460px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  corePlugins: {
    container: false,
  },
  plugins: [
    require('tailwindcss-animate'),
    require('tailwindcss-safe-area'),
    require('@tailwindcss/typography'),
  ],
};
